### ISSUE TITLE
offline_packages = failed_packages[4][2]

### ISSUE THREAD

**Issue by Gutz-Pilz** [rix1337/RSScrawler#319]
mein rsscrawler funktioniert nicht mehr
nutze die myjdownloader funktion von JD nicht mehr.

kann man den rsscrawler ohne myjd nutzen?

den error den ich bekomme

```
--------Alle Suchfunktion gestartet.--------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rsscrawler/RSScrawler.py", line 110, in crawler
    offline_packages = failed_packages[4][2]
TypeError: 'bool' object is not subscriptable
```

**Comment by Gutz-Pilz** [comment]
okay. dein fix hat funktioniert.
er crawlt und findet wieder schön.
allerdings legt er keine crawljob-datei ab
Das ist meine config.
```
  rsscrawler:
    container_name: rsscrawler
    image: rix1337/docker-rsscrawler
    stdin_open: true
    tty: true
    ports:
      - "6060:9090"
    volumes:
      - '/root/.configs/.rsscrawler/:/config:rw'
      - '/root/.configs/.jdownloader2:/jd2:rw'
    environment:
      - PUID=1000
      - PGID=100
      - LOGLEVEL=DEBUG
    restart: always

```
